### ISSUE TITLE
Pass information to callback functions

### ISSUE THREAD

**Issue by kdo** [10up/component-accordion#23]
**Is your feature request related to a problem? Please describe.**
Seen on projects, sometimes content need to be initialized/created on open, or clients want the window to scroll to the open accordion item.

**Describe the solution you'd like**
It would be nice to have some information about the opened/closed items in the callback functions arguments maybe?

**Describe alternatives you've considered**
n/a

**Comment by Firestorm980** [comment]
@timwright12 Ping on this for you for review/merge.

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/15
