### ISSUE TITLE
Incorrect entry file in package.json

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/component-accordion#26]
**Describe the bug**
Incorrect entry file in JS, links to src, but should use transpiled version in dist.
https://github.com/10up/component-accordion/blob/b7169a8/package.json#L6

Causing this issue in downstream dependencies: https://github.com/10up/theme-scaffold/issues/183

**Comment by timwright12** [comment]
hold off on fixing this one

**Comment by nicholasio** [comment]
This has been addressed here: https://github.com/10up/component-library/pull/10
