### ISSUE TITLE
Sub-accordions don't work

### ISSUE THREAD

**Issue by junaidbhura** [10up/component-accordion#28]
**Describe the bug**
This component only supports single-level accordions. We are working on a project where we need to use this component in a nested way. So the accordion content would have another accordion within it.

**To Reproduce**
1. Create an accordion
2. Add another accordion within it's content

**Expected behavior**
Both accordions work independently of each other.

**Additional context**
The issue is caused by this line: https://github.com/10up/component-accordion/blob/master/src/accordion.js#L84

```js
accordionArea.querySelectorAll( '.accordion-header' );
```

We'd need to update that function to have an equivalent of:

```js
accordionArea.querySelectorAll( ':scope > .accordion-header' );
```
So the accordion only looks for, and attaches events for it's own direct descendants.

**Comment by timwright12** [comment]
@junaidbhura we just published in v1.1 to npm this morning. Thanks for pointing it out!
