### ISSUE TITLE
The component is prone to leak memory

### ISSUE THREAD

**Issue by eugene-manuilov** [10up/component-accordion#35]
**Describe the bug**

The component adds event listeners during setup process, but it doesn't remove it when the component is not needed anymore on the page. It means that if we add and remove accordions programmatically on the same page, it won't be garbage collected and remain in the memory.

**Expected behavior**

There should be a method to destroy accordion when it's not needed anymore.

**Comment by timwright12** [comment]
@eugene-manuilov what are your expectations of the destroy method? Just removing the listeners?

**Comment by nicholasio** [comment]
Closed in favor of: https://github.com/10up/component-library/issues/14
