### ISSUE TITLE
Enhance animation guidance / capabilities

### ISSUE THREAD

**Issue by joesnellpdx** [10up/component-accordion#39]
**Issue / Enhancement**
Although you can use the callbacks to provide some animation to the accordions, there can be challenges with focus states, adding listeners to `transitionend`, and accounting for the according content height for consistent smooth transitions.

**Solution**
- documentation and guidance for adding animation to accordions
- add any necessary callbacks, listeners, or enhancements to allow adding animations to be efficient and easy

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/13
